[package]
name = "zigup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
indexmap = { version = "2.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
ureq = { version = "2.7", features = ["json"] }
xz2 = "0.1"
